### ISSUE TITLE
Make setting page cleaner

### ISSUE THREAD

**Issue by bigshans** [Beaver-Notes/Beaver-Notes#173]
**Is your feature request related to a problem? Please describe.**

Well, more and more settings put it there make look a little ugly.

![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/ba4eea99-72ab-49d2-9f17-b0e7df7701b7)

**Describe the solution you'd like**
It would be better to categorize these settings and place them under different settings pages.

It would also be beneficial to have more descriptions for these settings. All the settings are currently piled up under 'General,' which seems too crowded.

I think the current settings can be divided into Interface Settings, Sync Settings, and some general settings related to applications. Do you have any other insights?

**Comment by Daniele-rolli** [comment]
It's a great idea! It's something I've actually thought about, and as a matter of fact, I've been doing something similar with Beaver Pocket. So, we could divide them, as you said, into Interface or Appearance, Sync, and General. It will definitely help make the app feel less crowded and the settings less intimidating.

**Comment by bigshans** [comment]
![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/822ffa39-4d4a-48fd-8a89-5f5d24342f4b)

I think it may not be appropriate to call it "Editor Options", because "Clear Font" and "Hidden Menu Bar" obviously affect more than just the edit page. Perhaps it is called "Appearance Options", "Page Options" or any other name could be better?  I'm not very sure.

It's best to standardize the capitalization of the first letter.

Additionally, adding more space at the bottom could be better. The space at the bottom of the page is narrow. For example, this is the bottom of Thunderbird's settings page. They have left more space and look much more comfortable.

![图片](https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/2a36ac4d-d838-47e7-b8d4-e4af96805d2e)

**Comment by Daniele-rolli** [comment]
I've pushed commit dbc9cff to fix the padding issue and changed "Editor Options" to "Interface Options." By the way, I was thinking about creating an organization for Beaver Notes to move the project there so that it's easier to contribute, and long-term contributors can also have access to the organization. What do you think about this idea?

**Comment by bigshans** [comment]
Feel better than before.

> By the way, I was thinking about creating an organization for Beaver Notes to move the project there so that it's easier to contribute, and long-term contributors can also have access to the organization.

It's a great idea! I think it's OK!
