### ISSUE TITLE
Indentation error in code block

### ISSUE THREAD

**Issue by gamadev3** [Beaver-Notes/Beaver-Notes#195]
**Bug Description**
When we insert a block of code, when we press the 'tab' key to indent, it moves the entire block of code and not just the line we are on.

**To Reproduce**
1. Go to any page
2. Click on code block
3. Try press Key Tab for indentation.
4. Observe the error.

**Expected Behavior**
In others apps like Notion, Obsidian when press the tab key, an identation is made.

**Desktop:**
- OS: Linux Mint 21.3 Cinnamon
- Application Version: 3.2.0 - AppImage x64

https://github.com/Beaver-Notes/Beaver-Notes/assets/140192547/c5bf61f1-dccf-46df-8120-ff36fb3cbaef

**Comment by Daniele-rolli** [comment]
Thanks for the feedback. I've looked into it and promptly fixed it. The fix will be available in release 3.3.0, which should come out shortly.

https://github.com/Beaver-Notes/Beaver-Notes/assets/67503004/ceae294f-7fa7-4e36-a810-6a098301d3fb

**Comment by gamadev3** [comment]
Hi @Daniele-rolli. Thank you.
