### ISSUE TITLE
In a block of code, pressing the Tab key does not indent 4 spaces properly

### ISSUE THREAD

**Issue by auendx** [Beaver-Notes/Beaver-Notes#197]
**Bug Description**
Hello, in the text of the code block, press the Tab key can not normally indent 4 spaces, but to transform the focus on other controls. A later version can correct this error.

**Comment by Daniele-rolli** [comment]
Hi there! Thanks for the feedback. We're already aware of the issues with the tab behavior in the commit related to issue #195.
