### ISSUE TITLE
Is it possible to replace the default ctrl+shift+z with ctrl+z?

### ISSUE THREAD

**Issue by Colezwhy** [Beaver-Notes/Beaver-Notes#207]
Since in other scenarios I used ctrl+z as undo, it will be more convenient to give a feature to that.

**Comment by Daniele-rolli** [comment]
Thanks for sharing your issue! I tested it on both macOS and Windows 11 and confirmed that Ctrl+Z is used to undo in Beaver Notes. Could you please provide more information so I can better understand your problem? Thanks!

**Comment by Colezwhy** [comment]
> Thanks for sharing your issue! I tested it on both macOS and Windows 11 and confirmed that Ctrl+Z is used to undo in Beaver Notes. Could you please provide more information so I can better understand your problem? Thanks!

Oh it is fixed now, thanks !
