### ISSUE TITLE
"Focus Mode" on Ultra Wide Monitor Fails

### ISSUE THREAD

**Issue by vorwd** [Beaver-Notes/Beaver-Notes#214]
**Bug Description**
"Focus Mode" being toggled in the menu bar (i guess it would be called) becomes blank screen, and then ESC from that failed focus mode does not allow Beaver-Notes to recover to standard size/layout.  ~~This seems to be an Ultrawide monitor issues, as I did not experience this when changing the resolution to 1024x768.~~ I tested it again, and the result is the same regardless of resolution.

**To Reproduce**
1. Change resolution to 5120x1440 (32:9) (also running at 119.97Hz if that would impact)
          - this doesn't seem to be any impact on the bug, as I tested with multiple resolutions after reporting the bug, and it results in the same
2. Go to **menu/format bar** in **note edit**
3. Click on **focus mode**
4. Observe the error -- Beaver-Notes go _full screen/focus mode_ and no content is showed, only the "off black/grey" colour background.
5. Hit ESC to exit **focus mode** but Beaver-Notes does not recover and show content again; must exit application and then it works as expected, in non-focus mode.  Repeat and the same thing happens.
6. I can do "app switcher" in Gnome, and see Beaver is a big Beaver, and is blank also. 

**Expected Behavior**
I have not been able to see what **Focus Mode** actually does, but I would assume Beaver-Notes becomes full screen to take away distractions.

**Screenshots**
![image](https://github.com/user-attachments/assets/dd6fc66b-9bee-4334-8ad7-664bfc8c8be1)
_view via task switcher_

![image](https://github.com/user-attachments/assets/12d1b2b4-4590-440f-8c09-89e5d1232ad4)
_this looks like an empty screen shot, but this is the bug, with a screenshot of the whole screen_

![image](https://github.com/user-attachments/assets/d4da31b2-553c-4308-abef-f9eb18d09efe)
_after hitting ESC, Beaver-Notes does not recover_

**Desktop (please complete the following information):**
- Device Specification: 
- OS: 
![image](https://github.com/user-attachments/assets/5f603acc-1239-4dc3-9c5e-241057563456)
_interesting, Neofetch is reporting my resolution as 3840x1080, but Gnmome is reporting it as 5120x1440_

- Application Version: 3.4.0 via Flathub, installed via Gnome Software GUI

**Additional Context**
[journal.txt](https://github.com/user-attachments/files/16185286/journal.txt)

Journal output for the time period of bug recreation -- there are issues in there for gvfsd-fuse, which is not related to the bug report being submitted here, but they are related to Beaver (I had previously asked about this on Reddit and am working through a workaround based on feedback there, so likely to just disregard the gvfsd issues even though are pointing at Beaver-Notes.  

_If you believe you/someone can assist with the gvfs issues (syncing Beaver to Onedrive or Google Drive via gvfs-mount with Gnome integration) seen in the Journal extract, let me know and i can raise a separate bug report for this._

**Comment by vorwd** [comment]
Just on my p.s. comment:

**Comment by Daniele-rolli** [comment]
Thanks for the feedback! I'll look into the issue with focus as soon as I can. I've tested focus mode on my Debian Trixie install, and everything seems to work fine. However, since you have an Nvidia GPU, it could be a problem with either X11 or Wayland. I'll do some more research and get back to you.

Regarding gvfs, I've done some digging and found out that Beaver uses chmod on Linux for the file-assets folder, which gvfs doesn't seem to like. I'll work on the modifications and see if they can be implemented. By all means, feel free to open another issue regarding gvfs.

**Comment by vorwd** [comment]
Thanks for the reply.  For full transparency, I am unlikely to personally utilise focus mode, but I was playing around with everything in the application to see what was what as I just started using it.. then came across the bug.  

I will give it a test on my Ubuntu 22.04 with xfce and let you know -- but yea, still with the Nvidia GPU, as it's dual-boot on the same machine.

**Comment by vorwd** [comment]
Tested on xUbuntu with the same result, FYI -- but as mentioned, same hardware.  Nothing in journal. 
![image](https://github.com/user-attachments/assets/352cddc7-6ee7-43e1-8438-fa401bbe6e1a)



Freshly install Beaver-Notes via .deb package.

![image](https://github.com/user-attachments/assets/1b83f31c-8098-4ccf-bc72-4c98020d5aae)

![image](https://github.com/user-attachments/assets/e9194f30-6288-4b23-aad4-e1098ccdd3e6)

**Comment by Daniele-rolli** [comment]
I've addressed the focus mode issue, which was caused by the interface size. I also managed to address the issues with GVFS. When exporting, it will use the `cp` command to sync with GVFS. However, this is quite slow, so auto-sync is not recommended for GVFS drives.

**Comment by vorwd** [comment]
Well done!  Look forward to giving it a whirl!
