### ISSUE TITLE
broken github link

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Beaver-Notes/Beaver-Notes#216]
If I visit https://github.com/Beaver-Notes/Beaver-Notes?tab=readme-ov-file and scroll down and click link I get dead page.

![image](https://github.com/user-attachments/assets/f71590df-3f2b-488c-9914-7875a13396d8)

https://beavernotes.com/package-manager.html = dead

![image](https://github.com/user-attachments/assets/6372d910-802f-45c4-ab59-bb214f2cf297)

**Comment by Daniele-rolli** [comment]
Thanks for pointing that out. We recently updated our website and forgot to update some links, which have now been corrected. Thanks again.
