### ISSUE TITLE
Release portable ZIP for Windows without autoupdater, works better with package managers like Scoop and WinGet

### ISSUE THREAD

**Issue by o-l-a-v** [Beaver-Notes/Beaver-Notes#219]
**Is your feature request related to a problem? Please describe.**

Would be great if Beaver Notes could be released as portable `.ZIP` packages to, without the autoupdate functionality built in, as that would work better with package managers like Scoop and WinGet.

Related feature request to put Beaver Notes in the standard "Extras" Scoop bucket, would work even better with a portable ZIP instead:

* <https://github.com/Daniele-rolli/Beaver-Bucket/issues/1>

**Describe the solution you'd like**

Described already.

**Describe alternatives you've considered**

None yet.

**Additional context**

None yet.

**Comment by Daniele-rolli** [comment]
Beaver Notes already offers a portable version, and creating a zip file will be a priority in the next version. However, the portable version does not store user data on the device's storage; instead, it saves it in the same location as the executable. Portable packages are designed to be mobile (pun unintended), so data must remain in the same location. This could potentially cause issues if installed via a package manager.

**Comment by o-l-a-v** [comment]
Hmm. The portable should work great with Scoop, as you can tell it to persist some directories on update.

But the portable exe is not signed, so it gets blocked by SmartScreen, at least on my Windows.

**Comment by o-l-a-v** [comment]
Portable EXE works fine, ref: <https://github.com/Daniele-rolli/Beaver-Bucket/issues/1#issuecomment-2231301726>
