### ISSUE TITLE
Inconsistent naming of "Beaver Notes" on Windows (actual name, uninstall info, shortcut)

### ISSUE THREAD

**Issue by o-l-a-v** [Beaver-Notes/Beaver-Notes#220]
**Bug Description**

This app is named "Beaver Notes"? The shortcuts created on Windows is named "Beaver-notes" (dash and lower "N"), while the uninstall info added to Windows Registry is "Beaver-Notes" (dash and upper "N").

**To Reproduce**

Install Beaver Notes v3.4.0 on Windows.

**Expected Behavior**

Should have the same name everywhere. The app name itself, shortcuts, uninstall info.

**Screenshots**

<img width="796" alt="image" src="https://github.com/user-attachments/assets/f3a24328-415e-4d0d-afaa-bd5b8bda2e8f">

**Desktop (please complete the following information):**

Not relevant.

**Additional Context**

Not relevant.

**Comment by Daniele-rolli** [comment]
Thanks for pointing that out. The actual package name is "Beaver-notes" according to the packages.json. Therefore, the shortcut shows "notes" without a capital letter. You can change the shortcut name if it bothers you. However, if I were to change the package name to start "Notes" with a capital letter, it would mean messing up the package, which is not ideal. Sorry for the inconvenience.

**Comment by o-l-a-v** [comment]
It's no inconvenience for me. This was more of note to you if consistent branding / app name is important.

**Comment by Daniele-rolli** [comment]
Thanks for the tip! I'll update what I can to ensure a more consistent branding.

**Comment by Daniele-rolli** [comment]
I’ve seen the work you’ve done to include Beaver in the Scoop repo, and it’s impressive. Thanks a lot! I’ve already updated the website to ensure that everyone uses the Scoop repo instead of our own. The original repo will be used as a fallback in case the Scoop repo encounters issues. Thanks again!

**Comment by o-l-a-v** [comment]
You're welcome! 🙂 I used it as a opportunity to learn more about Scoop and manifest authoring. I'd call it a win win!
