### ISSUE TITLE
Preview of KaTeX equations lag behind formula

### ISSUE THREAD

**Issue by maximmaxim345** [Beaver-Notes/Beaver-Notes#221]
**Bug Description**
Preview of KaTeX equations lag behind formula.

**To Reproduce**
1. Create a new multi line KaTeX formula and click on it.
2. Type in some character like 'a', the preview still says 'Empty'
3. Type in a second  'a', the preview now shows 'a'

**Expected Behavior**
The preview should update after the user has changed the expression.

**Screenshots**
![image](https://github.com/user-attachments/assets/f1af2c9c-d6c0-4e23-b8a9-60b533129ff8)

**Desktop (please complete the following information):**
- OS: Arch linux, Flatpak
- Application Version: 3.4.0

**Comment by Daniele-rolli** [comment]
Thanks for reporting this issue! I've fixed it, and I'm happy to say that the math block now works as expected and everything renders in real time. This change will be included in the upcoming version 3.5.0
