### ISSUE TITLE
Releases hash / checksum for Windows mixes portable and setup + portable has wrong file name

### ISSUE THREAD

**Issue by o-l-a-v** [Beaver-Notes/Beaver-Notes#223]
**Bug Description**

### Releases hash / checksum for Windows mixes portable and setup

It seems that the SHA256 checksums in release v3.4.0 has mixed up setup releases with portable releases for Windows.

* <https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/3.4.0>

|File |Claimed |Actual
|:--|:--|:--
[Beaver-notes.3.4.0.portable.exe](https://github.com/Beaver-Notes/Beaver-Notes/releases/download/3.4.0/Beaver-notes.3.4.0.portable.exe) |`9d7fdffb052dc0aa699124adf607a13b0de5a0fc33bab2099cccc837af1a3963` |`1db43e5bf3aa22afea43cb404dca51418a01417a28ffba6e75417ae1464fae90`
|[Beaver-notes.Setup.3.4.0.exe](https://github.com/Beaver-Notes/Beaver-Notes/releases/download/3.4.0/Beaver-notes.Setup.3.4.0.exe) |`1db43e5bf3aa22afea43cb404dca51418a01417a28ffba6e75417ae1464fae90` |`9d7fdffb052dc0aa699124adf607a13b0de5a0fc33bab2099cccc837af1a3963` 

### Release hashes for windows portable and setup uses wrong file name

Take portable for example. SHA256 file names in release:

* arm64: `Beaver-notes 3.4.0.arm64.exe`
* x64: `Beaver-notes 3.4.0.exe`

Actual file names:

* arm64: `Beaver-notes.3.4.0.portable.arm64.exe`
* x64: `Beaver-notes.3.4.0.portable.exe`

**To Reproduce**

<https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/3.4.0>

* Download x64 or arm64 **portable**, get SHA256 shecksum.
* See that checksum matches **setup** checksum from release notes.

**Expected Behavior**

Shoul be the other way around.

**Screenshots**

*Not relevant.*

**Desktop (please complete the following information):**

*Not relevant.*

**Additional Context**

*Not relevant.*

**Comment by Daniele-rolli** [comment]
Thanks for the heads-up. I corrected the hash in the release.

**Comment by o-l-a-v** [comment]
I assume the release info is autogenerated? Will it be correct next release too then? 🙂

**Comment by o-l-a-v** [comment]
File names linked to the hash are still wrong.

**Comment by Daniele-rolli** [comment]
Thanks for pointing that out! I've updated the file names just now.
