### ISSUE TITLE
Color picker for tags & highlights

### ISSUE THREAD

**Issue by RainSharky** [Beaver-Notes/Beaver-Notes#229]
**Is your feature request related to a problem? Please describe.**
I am a very visual and color orientated person, and only having yellow as an option makes it difficult for me.

**Describe the solution you'd like**
I would love to have some sort of color picker under the highlight menu. Another possibility would be marking text or a tag and then right-click to have a context-menu.

**Describe alternatives you've considered**
none so far

**Additional context**
![image](https://github.com/user-attachments/assets/3faa541a-eb8c-4fa5-9e42-75285b619d10)
(From AppFlowy)

**Comment by Daniele-rolli** [comment]
Thanks for the suggestion! A color picker for tags and highlights is a great idea, and I'll work on implementing it as soon as possible. However, we are currently focusing on the mobile app before adding any major features to the desktop version. Thank you for your understanding. I hope you'll continue to enjoy Beaver Notes as much as we do.

**Comment by Daniele-rolli** [comment]
Hi there, Version 3.6.0 is right around the corner. As you can see, we’ve implemented colors for highlighters. However, we decided against implementing colors for tags, as it would require rewriting a core part of the application, which could potentially cause issues with existing labels. I hope the highlighter feature is helpful. I’m sorry we couldn’t fully resolve your issue. I’ll make sure to add highlighter colors to the mobile app as well. Thanks again for opening this issue, and I hope you enjoy using Beaver Notes!
