### ISSUE TITLE
Duplicate Japanese text in header

### ISSUE THREAD

**Issue by nagayasuu** [Beaver-Notes/Beaver-Notes#230]
**Bug Description**
Duplicate Japanese text in header.

**To Reproduce**
1. Open a note
2. Type Japanese characters in header.

**Expected Behavior**
Characters are entered without duplication.

**Screenshots**
[Screencast from 2024-08-11 21-57-37.webm](https://github.com/user-attachments/assets/eca7b4b5-f3cf-46fa-bf3f-44e61ce21b69)

**Desktop (please complete the following information):**
- OS: Ubuntu 24.04 LTS
- Application Version: 3.0.5

**Additional Context**
This issue did not occur in version 3.0.4.

**Comment by Daniele-rolli** [comment]
Thanks for reporting this bug. I'm quite ignorant about how Japanese works but as much as I managed to understand when typing in Japanese you enter the sounds in Romaji, converting them to Kana, and then select the appropriate Kanji as needed which is the one that jets duplicated in this case. I've tried to replicate this issue in Mac OS and couldn't so it might be specific to ubuntu or the package manager you used to install Beaver.  Did you install the application through flatpak or using a .deb file?

**Comment by Daniele-rolli** [comment]
Ok so I browsed the web and found out this from the obsidian forum which suggests this might be a software issue we can surely mitigate it but I don't know if it's completely solvable "If you range-select a string that includes the character immediately following symbols such as quotation (>), link ([[,]]), highlight(==), heading or tag (#), etc., and then type a new string and try to convert it to kanji, the string is duplicated." [source](https://forum.obsidian.md/t/duplication-of-characters-during-kanji-conversion-in-a-japansese-ime-atok-still-remains-in-some-places/40827/8)

**Comment by bigshans** [comment]
One workaround is using IME without pre-commit. I tested Weasel on Windows and Fcitx on Linux. They work fine after turning off pre-commit. Tiptap has not fixed this bug, and They seem not to plan to fix it. Using custom `NodeView` will cause this problem in some cases.

**Comment by bigshans** [comment]
I think if you think the folding is not very necessary and the workaround is not very convenient, we can also provide an option to turn it off. What do you think?

**Comment by Daniele-rolli** [comment]
I think you are right. Since folding seems to negatively impact the user experience when writing in Japanese, we should add a way to either disable it through a keyboard shortcut or include it in settings. If you could take care of this, it would be brilliant, as I'm still working on Beaver Pocket. Speaking of Pocket, I've had some issues porting folding there, but that's an issue for another time.

**Comment by nagayasuu** [comment]
@Daniele-rolli @bigshans 
Thank you for checking.

I also use fcitx, and I was able to enter the correct information after trying the workaround.

I also agree with the following, it would be helpful to have this option.
> I think if you think the folding is not very necessary and the workaround is not very convenient, we can also provide an option to turn it off. What do you think?

**Comment by bigshans** [comment]
OK, I've put it into my Todo list. It may take some time. after all, there are data integrity issues to consider after turning off the option.
