### ISSUE TITLE
Drawing Support

### ISSUE THREAD

**Issue by Tahinli** [Beaver-Notes/Beaver-Notes#233]
**Describe the solution you'd like**
I would like to draw in Beaver Notes. I have a drawing tablet and while studying something like mathematics, I have to draw questions and answers. Also I need to take notes about theoretical subjects so beaver notes will be perfect fit if you add a chance to draw. I'm sure a lot of people have a lot of cases about it.

In the first time you don't even need to add support for drawing tablets. if you can just let us to draw with mouse and give ability to define shortcuts for erasing and dragging an element, it will be enough for most situations.

**Comment by Daniele-rolli** [comment]
Drawing is something I was considering, but it fell into the backlog. However, we could add it to the new release of Beaver Notes, as it would also be beneficial for Beaver Pocket. My current idea for implementing drawing is to use the same approach Apple uses with Pages, which allows both text and handwritten content to coexist in the same note.

Here's an example:

![IMG_F9FF3FBACC1B-1](https://github.com/user-attachments/assets/f2ef78f4-88fe-4f06-815a-2eebe58fd695)

**Comment by Daniele-rolli** [comment]
Here's the finished product. It includes a pen and highlighter with three preset thicknesses, as well as an eraser. We’ve also added undo and redo buttons and a color picker. The canvas can be resized vertically. It's quite basic, but it should get the job done. What do you think?

<img width="888" alt="Screenshot 2024-09-01 at 12 16 39 AM" src="https://github.com/user-attachments/assets/90ec758a-4036-4c6e-8673-5fd042291475">

**Comment by Tahinli** [comment]
Seems very cool. Thanks a lot. If you have a chance to give shortcuts and give power to user to assign them as their wish, it will be pretty cool. I'm going to assign mouse left to pen, mouse right to eraser, CTRL+Z command to trigger undo and CTRL+SHIFT+Z to redo. It will also allow me to use this awesome feature with my drawing tablet. Thanks a lot for your effort. When you finish please let me know so I can be able to translate these new features also (I'm the Turkish translator).

**Comment by Daniele-rolli** [comment]
I'll make sure to add custom keyboard shortcuts to the roadmap, but they probably won't make it into the next version. I've updated the component to feature grid, dotted, and ruled paper since I figured people like you, who use it for math or writing, would benefit from proper layouts. I also redesigned the resize handle to make it easier to use with a Surface Pen or any touchscreen device with a stylus.

<img width="879" alt="Screenshot 2024-09-02 at 9 47 17 AM" src="https://github.com/user-attachments/assets/5dbc23ca-902c-4fb5-8915-1cb8d20f0cca">

**Comment by Tahinli** [comment]
It's getting better, thanks a lot.

**Comment by Daniele-rolli** [comment]
I'll close this issue as complete since there's nothing more to be done and the translations have already been pushed. Please check the Turkish translation, as there should only be the word 'Draw' to translate. Thanks again for opening this issue and helping us translate Beaver Notes into Turkish.
