### ISSUE TITLE
Zoom in/out

### ISSUE THREAD

**Issue by jjezik82** [Beaver-Notes/Beaver-Notes#238]
Hi there, I have app installed on linux Fedora and I accidentaly zoomed out app with Ctrl- and I  tried to zoom it in with Ctrl+ but it didn't work. I didn't find any shortcut for this. I managed to somehow reset it with Ctrl+m. So I'm just wondering if there's any documented shortucts for this, or it's just a bug? Thanks.

**Comment by Daniele-rolli** [comment]
Thanks for reporting this issue. I tested it on Fedora and found that you can use Ctrl - to zoom out, but you need to use Ctrl Shift + to zoom in with an American keyboard layout. I'll work on adding support for zooming in by pressing Ctrl +. If this issue occurs again, you can reset the zoom by going to the settings and selecting the default option.

![Screenshot 2024-09-04 at 10 45 52 AM](https://github.com/user-attachments/assets/10bf0560-68a5-4879-85f3-0f53c2f042fa)

**Comment by jjezik82** [comment]
Thank you.
