### ISSUE TITLE
Wrong name for "video" button

### ISSUE THREAD

**Issue by Tahinli** [Beaver-Notes/Beaver-Notes#239]
The video button is no longer just for video (we have also drawing button in this section "thanks for it again") so I think there should be a rethink about it
![image](https://github.com/user-attachments/assets/101e5d67-c360-4b27-a8af-6d10958da7c0)

**Comment by Daniele-rolli** [comment]
Thanks for reporting this! It's just a UI oversight. I'll fix it and update the app within a week to avoid releasing updates back to back.
