### ISSUE TITLE
Add Emphasizer for Buttons in Drawing

### ISSUE THREAD

**Issue by Tahinli** [Beaver-Notes/Beaver-Notes#240]
**Is your feature request related to a problem? Please describe.**
Hi, in drawing section it's hard to know if pen, eraser or highlighter is selected.

**Describe the solution you'd like**
If you can keep the shape around them(when we click pen, eraser or highlighter buttons an orange shape spawns around them) it will let user to know which button is selected. 

**Describe alternatives you've considered**
Pen, eraser, highlighter images can be added for mouse cursor. When we press buttons cursor will change

**Comment by Daniele-rolli** [comment]
I'll work on adding a border or changing the color of the selected tool. This will be updated in the next version, which, due to these bugs, will be released within a week.

**Comment by Daniele-rolli** [comment]
This issue has been fixed with [commit 634842680b](https://github.com/Beaver-Notes/Beaver-Notes/commit/634842680b41310429b9147840bf7aaa37fa052d).

**Comment by Tahinli** [comment]
Right now I only have emphasizer for eraser.
Have you done this on purpose or is this a bug ?

https://github.com/user-attachments/assets/7a268bf2-f379-479f-ac62-248d11a67525

**Comment by Daniele-rolli** [comment]
I’m so sorry! This issue was supposed to be fixed before it entered production. I’ll make sure it gets patched in the next version. I hope this doesn’t cause any problems and that you’ll continue to enjoy using Beaver Notes.

**Comment by Tahinli** [comment]
> I’m so sorry! This issue was supposed to be fixed before it entered production. I’ll make sure it gets patched in the next version. I hope this doesn’t cause any problems and that you’ll continue to enjoy using Beaver Notes.

It's not a big deal at all, I just wanted to inform you. 👍
