### ISSUE TITLE
Spellcheck doesn't provide suggestions

### ISSUE THREAD

**Issue by beraneck** [Beaver-Notes/Beaver-Notes#241]
**Bug Description**
When a spelling mistake is found, it is underlined, but there are no suggestions when you right-click on the word in question.

**To Reproduce**
1. enable spellcheck
2. make a spelling mistake
3. right click on the word

**Expected Behavior**
On right click on the underlined word, a contextual menu shows some spelling suggestions.

**Desktop (please complete the following information):**
Ubuntu 22.04.4 LTS
Beaver Notes 3.6.0

**Comment by Daniele-rolli** [comment]
Thanks for opening this issue. I've just added support for contextual menus, which will be available starting with version 3.7.0. We plan to release it within a week at most. Here’s a little demo of the feature.

https://github.com/user-attachments/assets/675a8e96-1061-4f41-99cb-e705444e0625
