### ISSUE TITLE
Add Translation for Page Types in Drawing

### ISSUE THREAD

**Issue by Tahinli** [Beaver-Notes/Beaver-Notes#242]
Hi,

I think we should be able to translate these page types in drawing. I didn't see them in our translation system as a word so couldn't translate.

Plain
Grid
Ruled
Dotted

<img width="452" alt="image" src="https://github.com/user-attachments/assets/63cfbd7c-4498-41a0-a48e-122e72c5f42c">

**Comment by Daniele-rolli** [comment]
I've just updated the component, and the translations should now be available on the platform.
