### ISSUE TITLE
Problem with .md import

### ISSUE THREAD

**Issue by SrsBusinesx** [Beaver-Notes/Beaver-Notes#244]
**Bug Description**
If i want to import .md files with your way (folder;file-assets;notes-assets). It doesn't work.
I always get errors.

**To Reproduce**
Normal way to import markdown files.

**Expected Behavior**
Correct imported markdown files.

**Screenshots**
Console Log:

markdown.js:722 Error listing directory: TypeError: Cannot read properties of null (reading 'checked')
    at markdown.js:226:77
    at Array.map (<anonymous>)
    at f (markdown.js:225:18)
    at async Promise.all (index 42)
    at async pme (markdown.js:639:23)
    at async mme (markdown.js:692:36)
    at async g (Index.vue:554:9)
    
Index.vue:536 Error: ENOENT: no such file or directory, open 'path/to/import/folder/data.json'
f @ Index.vue:536
index.js:987 [tiptap warn]: Duplicate extension names found: ['doc', 'text', 'gapCursor', 'hardBreak', 'codeBlock', 'code', 'heading']. This can lead to issues.
resolve @ index.js:987
Show 1 more frame
Show less
AppSidebar.vue:305 Error: The "path" argument must be of type string. Received null
    at Proxy.R (AppSidebar.vue:199:33)
 
---   
 const folderPath = path.join(exportPath, folderName);
---
const checkbox = li.querySelector('input[type="checkbox"]');
                  const checked = checkbox.checked;
                  return {
                    type: 'taskItem',
                    attrs: { checked },
                    content: [
                      {
                        type: 'paragraph',
                        content: (
                          await Promise.all(
                            Array.from(li.childNodes).map(
                              convertElementToTiptap
                            )
                          )
                        ).filter(Boolean),
                      },
                    ],
                  };
---
 .map(async (li) => {
                  const checkbox = li.querySelector('input[type="checkbox"]');
                  const checked = checkbox.checked;
                  return {
                    type: 'taskItem',
                    attrs: { checked },
                    content: [
                      {
                        type: 'paragraph',
                        content: (
                          await Promise.all(
                            Array.from(li.childNodes).map(
                              convertElementToTiptap
                            )
                          )
                        ).filter(Boolean),
                      },
                    ],
                  };
---
        const { title, content } = await convertMarkdownToTiptap(
          markdown,
          id,
          directoryPath
        );
---

Apparently these parts are making problems especially.

----
**Desktop (please complete the following information):**
- OS: Windows 11
- Application Version: 3.6, Newest

**Additional Context**

**Comment by Daniele-rolli** [comment]
Hi there, Thanks for reporting this bug. I've just begun looking into it, and the issue seems to be related to how checklists are parsed. To better replicate the issue, could you specify the application you used to export these markdown files? I'll do my best to help fix this issue and find a workaround if possible; otherwise, the fixes will be featured in next week's version of Beaver Notes.

**Comment by SrsBusinesx** [comment]
The notes are from obsidian.
But that is only an error of the first file.

After i opened the issue i tried some things myself and as a last step I removed the first file.
After that I encountered many other errors.

In the nextfile are linked e-mail adresses (mailto: xx@xx) and that crashes, too.

It's kind frustrating, that the whole import crashes with the first error.
If the import would parse all files regardless of the number of errors it would be possible to have a complete list of errors for these files.

---

Thanks for your really quick answer!

**Comment by Daniele-rolli** [comment]
I've updated the markdown importer, which now processes files, collects errors, and leaves blank anything it fails to process. I've also updated the link handler to manage linked email addresses, but there are still some quirks to iron out.
