### ISSUE TITLE
Add Colours for Drawing

### ISSUE THREAD

**Issue by Tahinli** [Beaver-Notes/Beaver-Notes#249]
**Is your feature request related to a problem? Please describe.**
It's hard to explain something without colours, I'm trying to study math and whenever I want to draw function graph, I always miss colours.

**Describe the solution you'd like**
Add pencil colours

**Comment by Daniele-rolli** [comment]
The drawing board already supports using different pen colors. If you go to the bottom right corner, you can click the circle to select and change the pen’s color.

**Comment by Tahinli** [comment]
> The drawing board already supports using different pen colors. If you go to the bottom right corner, you can click the circle to select and change the pen’s color.

Sorry, my mistake. I thought it was something about pen size. Sorry again.

**Comment by Daniele-rolli** [comment]
No worries. Hope this solves everything. Have a great day and keep enjoying Beaver Notes!
