### ISSUE TITLE
添加不了图片，播放不了视频,导入导出无用

### ISSUE THREAD

**Issue by mychenjun** [Beaver-Notes/Beaver-Notes#259]
![动画](https://github.com/user-attachments/assets/d0f864b7-377e-4e8e-b494-282f597e8cb2)
这是什么问题?

**Comment by mychenjun** [comment]
What kind of question is that

**Comment by Daniele-rolli** [comment]
Thank you for the feedback! You might want to update to version 3.7.0. The buttons in the sidebar are for manual synchronization; it's a feature from older versions that we chose to keep. To use it, go to Settings > General and select the sync path. As for pictures and videos, please make sure the editor is focused. Also, try dragging and dropping to see if the issue occurs.
