### ISSUE TITLE
Option to adjust text width

### ISSUE THREAD

**Issue by runial** [Beaver-Notes/Beaver-Notes#263]
According to [generally accepted accessibility standards](https://www.w3.org/TR/WCAG21/#:~:text=Width%20is%20no%20more%20than,larger%20than%20the%20line%20spacing.), in some fonts (e.g., Arimo), there are often too many characters (>80) per line. This decreases readability.

I understand that some users prefer to have more characters or fewer characters per line. That's why I'm proposing an option to set the width in `rem` of the note text. I think this requires updating the `--selected-width` variable, which I believe is set at `54rem` for regular width and `68rem` for the "more space" option.

Due to how monospaced fonts and the `rem` unit works, monospaced fonts seem to somewhat meet the <80 character guideline, but that isn't a perfect solution. Thanks for reading!

**Comment by Daniele-rolli** [comment]
Thank you for your feedback! I've come up with a couple of potential solutions for the next version. Let me know which approach seems best: we could either use `c`h units for width control instead of `rem`, or dynamically adjust the width in `rem` based on the selected font.

**Comment by runial** [comment]
I think `ch` would probably work best. It's more intuitive and while it's not a perfect measure, if the user sets it to `80ch` it'll be a lot closer to 80 characters per line than `80rem`.

Could you elaborate on what you mean by dynamically adjust the width in `rem`?

Also, when the text is squished with CSS inspecting, the bar with text-editing features (bold, italic, etc.) is squished as well. Would it be realistic to have that bar specifically remain at full width even when the text width is changed? Thanks!

**Comment by Daniele-rolli** [comment]
Sorry for leaving you hanging. Here's what I've implemented so far. It's pretty basic and still needs some UI adjustments, but it provides the right degree of customization. You can click on the last button to input a custom width, which will be used and stored. If you switch to one of the predefined widths, the custom width will still be saved, just in case you change your mind later.
<img width="1512" alt="Screenshot 2024-11-18 at 9 27 32 AM" src="https://github.com/user-attachments/assets/bb7329e6-6cdb-4252-afca-25ddb3b0aaba">
