### ISSUE TITLE
Doesn't work if port 3000 is in use

### ISSUE THREAD

**Issue by dagelf** [Beaver-Notes/Beaver-Notes#265]
**Bug Description**
`Downloads/Beaver-notes-3.7.0.AppImage` doesn't run if port 3000 is in use. 

**To Reproduce**
$ python -m http.server 3000
$ Downloads/Beaver-notes-3.7.0.AppImage

**Expected Behavior**
Works

**Screenshots**
Ugly js error popup and nothing happens

**Desktop (please complete the following information):**
- OS: Ubuntu 22

**Additional Context**
If it must use a port, find an open one and start high. Or at least make it configurable...

**Comment by Daniele-rolli** [comment]
Thank you for your feedback. The feature that requires port 3000 was deprecated in commit 9b1a6bc and is scheduled for removal in version 3.8.0.
