### ISSUE TITLE
Some errors and Undo not working after embed

### ISSUE THREAD

**Issue by SpaceCoderPro** [Beaver-Notes/Beaver-Notes#266]
index.js:4536 [tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead. Found in extension: "noteLabel".
xv @ index.js:4536
Show 1 more frame
Show less
2index.js:4536 [tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead. Found in extension: "linkNote".
xv @ index.js:4536
Show 1 more frame
Show less
index.js:1275 [tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead. Found in extension: "search".
Yr @ index.js:1275
Show 1 more frame
Show less
AppSidebar.vue:697 Default path from local storage: C:\Users\samya\Documents\Notes
index.html#/note/z8I6xRVRN5nYynQmdi2Y8:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: DFtMTKhJ.ttf
index.js:987 [tiptap warn]: Duplicate extension names found: ['doc', 'text', 'gapCursor', 'hardBreak', 'codeBlock', 'code', 'heading']. This can lead to issues.
resolve @ index.js:987
Show 1 more frame
Show less
AppSidebar.vue:648 Data merged successfully.
jquery-migrate.min.js?m=1686289764:2 JQMIGRATE: Migrate is installed, version 3.4.1
step-1-the-daisy/:328 Unrecognized feature: 'web-share'.
ads:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
ads:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
ads:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
ads:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
38Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.

**Comment by SpaceCoderPro** [comment]
Some errors from Ctrl+Shift+I
This app seems to be built as Electron

**Comment by Daniele-rolli** [comment]
Thank you for bringing up these issues. We are aware of them, and they do not affect the app's functionality. These will be resolved in a future commit. Yes, the app is built using Electron, as it provides the most efficient and stable way to deliver a consistent experience across all three major operating systems without requiring separate versions for each.
